// Indian States and their major cities
export const INDIAN_STATES_AND_CITIES = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kurnool",
    "Rajahmundry",
    "Kadapa",
    "Kakinada",
    "Anantapur",
    "Tirupati",
    "Eluru",
    "Chittoor",
    "Machilipatnam",
    "Hindupur",
    "Srikakulam",
    "Bhimavaram",
    "Madanapalle",
    "Guntakal",
    "Dharmavaram",
    "Gudivada",
  ],
  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tezpur",
    "Bomdila",
    "Ziro",
    "Along",
    "Changlang",
    "Tezu",
    "Khonsa",
    "Namsai",
    "Seppa",
    "Daporijo",
    "Basar",
    "Roing",
  ],
  Assam: [
    "Guwahati",
    "Silchar",
    "Dibrugarh",
    "Jorhat",
    "Nagaon",
    "Tinsukia",
    "Tezpur",
    "Bongaigaon",
    "Dhubri",
    "North Lakhimpur",
    "Karimganj",
    "Sivasagar",
    "Goalpara",
    "Barpeta",
    "Diphu",
    "Mangaldoi",
    "Haflong",
    "Hailakandi",
    "Morigaon",
    "Golaghat",
  ],
  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Bihar Sharif",
    "Arrah",
    "Begusarai",
    "Katihar",
    "Munger",
    "Chapra",
    "Danapur",
    "Saharsa",
    "Sasaram",
    "Hajipur",
    "Dehri",
    "Siwan",
    "Motihari",
    "Nawada",
  ],
  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Korba",
    "Bilaspur",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Raigarh",
    "Ambikapur",
    "Mahasamund",
    "Dhamtari",
    "Chirmiri",
    "Janjgir",
    "Sakti",
    "Tilda",
    "Mungeli",
    "Naila Janjgir",
    "Champa",
    "Ratanpur",
    "Kanker",
  ],
  Goa: [
    "Panaji",
    "Vasco da Gama",
    "Margao",
    "Mapusa",
    "Ponda",
    "Bicholim",
    "Curchorem",
    "Sanquelim",
    "Valpoi",
    "Pernem",
    "Quepem",
    "Cuncolim",
    "Aldona",
    "Arambol",
    "Calangute",
    "Candolim",
    "Colva",
    "Anjuna",
    "Baga",
    "Morjim",
  ],
  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Navsari",
    "Morbi",
    "Mehsana",
    "Bharuch",
    "Vapi",
    "Veraval",
    "Porbandar",
    "Godhra",
    "Bhuj",
    "Surendranagar",
    "Gandhidham",
  ],
  Haryana: [
    "Faridabad",
    "Gurgaon",
    "Panipat",
    "Ambala",
    "Yamunanagar",
    "Rohtak",
    "Hisar",
    "Karnal",
    "Sonipat",
    "Panchkula",
    "Bhiwani",
    "Sirsa",
    "Jind",
    "Thanesar",
    "Kaithal",
    "Palwal",
    "Rewari",
    "Hansi",
    "Narnaul",
    "Fatehabad",
  ],
  "Himachal Pradesh": [
    "Shimla",
    "Solan",
    "Mandi",
    "Palampur",
    "Baddi",
    "Nahan",
    "Hamirpur",
    "Una",
    "Kullu",
    "Dharamshala",
    "Bilaspur",
    "Chamba",
    "Dalhousie",
    "Kangra",
    "Manali",
    "Kasauli",
    "Joginder Nagar",
    "Nurpur",
    "Rampur",
    "Kinnaur",
  ],
  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro",
    "Deoghar",
    "Phusro",
    "Hazaribagh",
    "Giridih",
    "Ramgarh",
    "Medininagar",
    "Chirkunda",
    "Pakaur",
    "Chaibasa",
    "Mihijam",
    "Chatra",
    "Gumla",
    "Dumka",
    "Madhupur",
    "Sahibganj",
    "Rajmahal",
  ],
  Karnataka: [
    "Bangalore",
    "Mysore",
    "Hubli-Dharwad",
    "Mangalore",
    "Belgaum",
    "Gulbarga",
    "Davanagere",
    "Bellary",
    "Bijapur",
    "Shimoga",
    "Tumkur",
    "Raichur",
    "Bidar",
    "Hospet",
    "Hassan",
    "Gadag-Betigeri",
    "Udupi",
    "Bhadravati",
    "Chitradurga",
    "Kolar",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Palakkad",
    "Alappuzha",
    "Malappuram",
    "Kannur",
    "Kasaragod",
    "Kottayam",
    "Pathanamthitta",
    "Idukki",
    "Wayanad",
    "Guruvayur",
    "Thalassery",
    "Kayamkulam",
    "Kanhangad",
    "Payyanur",
    "Koyilandy",
  ],
  "Madhya Pradesh": [
    "Indore",
    "Bhopal",
    "Jabalpur",
    "Gwalior",
    "Ujjain",
    "Sagar",
    "Dewas",
    "Satna",
    "Ratlam",
    "Rewa",
    "Murwara",
    "Singrauli",
    "Burhanpur",
    "Khandwa",
    "Morena",
    "Bhind",
    "Chhindwara",
    "Guna",
    "Shivpuri",
    "Vidisha",
  ],
  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Thane",
    "Nashik",
    "Aurangabad",
    "Solapur",
    "Amravati",
    "Kolhapur",
    "Sangli",
    "Malegaon",
    "Akola",
    "Latur",
    "Dhule",
    "Ahmednagar",
    "Chandrapur",
    "Parbhani",
    "Jalgaon",
    "Bhiwandi",
    "Nanded",
  ],
  Manipur: [
    "Imphal",
    "Thoubal",
    "Lilong",
    "Mayang Imphal",
    "Kakching",
    "Nambol",
    "Moirang",
    "Churachandpur",
    "Ukhrul",
    "Bishnupur",
    "Senapati",
    "Tamenglong",
    "Jiribam",
    "Moreh",
    "Noney",
  ],
  Meghalaya: [
    "Shillong",
    "Tura",
    "Jowai",
    "Nongstoin",
    "Baghmara",
    "Williamnagar",
    "Resubelpara",
    "Mairang",
    "Mawkyrwat",
    "Ampati",
    "Cherrapunji",
    "Dawki",
    "Khliehriat",
    "Nongpoh",
    "Ranikor",
  ],
  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Saiha",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Mamit",
    "Lawngtlai",
    "Saitual",
    "Khawzawl",
    "Hnahthial",
    "Zawlnuam",
    "Tlabung",
    "Bairabi",
    "Darlawn",
  ],
  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek",
    "Kiphire",
    "Longleng",
    "Peren",
    "Mon",
    "Noklak",
    "Chumukedima",
    "Tuli",
    "Jalukie",
  ],
  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Berhampur",
    "Sambalpur",
    "Puri",
    "Balasore",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Jeypore",
    "Barbil",
    "Khordha",
    "Bolangir",
    "Rayagada",
    "Angul",
    "Kendujhar",
    "Nabarangpur",
    "Koraput",
    "Paradip",
  ],
  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Firozpur",
    "Batala",
    "Pathankot",
    "Moga",
    "Hoshiarpur",
    "Malerkotla",
    "Khanna",
    "Phagwara",
    "Muktsar",
    "Barnala",
    "Rajpura",
    "Kapurthala",
    "Sangrur",
    "Fazilka",
  ],
  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Kota",
    "Bikaner",
    "Ajmer",
    "Udaipur",
    "Bhilwara",
    "Alwar",
    "Sikar",
    "Bharatpur",
    "Pali",
    "Sri Ganganagar",
    "Kishangarh",
    "Baran",
    "Dhaulpur",
    "Tonk",
    "Beawar",
    "Hanumangarh",
    "Churu",
    "Jhunjhunu",
  ],
  Sikkim: [
    "Gangtok",
    "Namchi",
    "Geyzing",
    "Mangan",
    "Jorethang",
    "Nayabazar",
    "Singtam",
    "Rangpo",
    "Yuksom",
    "Soreng",
    "Ravangla",
    "Pakyong",
    "Dentam",
    "Kalimpong",
    "Lachung",
  ],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Tiruppur",
    "Vellore",
    "Erode",
    "Thoothukkudi",
    "Dindigul",
    "Thanjavur",
    "Ranipet",
    "Sivakasi",
    "Karur",
    "Udhagamandalam",
    "Hosur",
    "Nagercoil",
    "Kanchipuram",
    "Kumarakonam",
  ],
  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahabubnagar",
    "Nalgonda",
    "Adilabad",
    "Suryapet",
    "Miryalaguda",
    "Jagtial",
    "Mancherial",
    "Nirmal",
    "Palwancha",
    "Kothagudem",
    "Bodhan",
    "Sangareddy",
    "Metpally",
    "Zaheerabad",
  ],
  Tripura: [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Kailasahar",
    "Belonia",
    "Khowai",
    "Pratapgarh",
    "Ranir Bazar",
    "Sonamura",
    "Kumarghat",
    "Ranirbazar",
    "Bishalgarh",
    "Teliamura",
    "Mohanpur",
    "Kamalpur",
  ],
  "Uttar Pradesh": [
    "Lucknow",
    "Gautam Buddha Nagar",
    "Greater Noida",
    "Kanpur",
    "Ghaziabad",
    "Agra",
    "Varanasi",
    "Meerut",
    "Allahabad",
    "Bareilly",
    "Moradabad",
    "Aligarh",
    "Gorakhpur",
    "Saharanpur",
    "Noida",
    "Firozabad",
    "Jhansi",
    "Muzaffarnagar",
    "Mathura",
    "Rampur",
    "Shahjahanpur",
    "Farrukhabad",
  ],
  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani-cum-Kathgodam",
    "Rudrapur",
    "Kashipur",
    "Rishikesh",
    "Ramnagar",
    "Pithoragarh",
    "Jaspur",
    "Kichha",
    "Manglaur",
    "Nainital",
    "Mussoorie",
    "Tehri",
    "Pauri",
    "Bageshwar",
    "Champawat",
    "Almora",
    "Rudraprayag",
  ],
  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Asansol",
    "Siliguri",
    "Bardhaman",
    "Malda",
    "Baharampur",
    "Habra",
    "Kharagpur",
    "Shantipur",
    "Dankuni",
    "Dhulian",
    "Ranaghat",
    "Haldia",
    "Raiganj",
    "Krishnanagar",
    "Nabadwip",
    "Medinipur",
    "Jalpaiguri",
  ],
};

// Get all state names
export const getIndianStates = () => {
  return Object.keys(INDIAN_STATES_AND_CITIES).sort();
};

// Get cities for a specific state
export const getCitiesForState = (state) => {
  return INDIAN_STATES_AND_CITIES[state] || [];
};

// Validate if a state exists
export const isValidState = (state) => {
  return Object.keys(INDIAN_STATES_AND_CITIES).includes(state);
};

// Validate if a city exists in a specific state
export const isValidCityInState = (city, state) => {
  const cities = getCitiesForState(state);
  return cities.includes(city);
};

// Validate complete location
export const validateLocation = (city, state, country) => {
  const errors = {};

  // Country must be India
  if (country !== "India") {
    errors.country = "Country must be India";
  }

  // State validation
  if (!state) {
    errors.state = "State is required";
  } else if (!isValidState(state)) {
    errors.state = "Please select a valid Indian state";
  }

  // City validation
  if (!city) {
    errors.city = "City is required";
  } else if (state && !isValidCityInState(city, state)) {
    errors.city = `Please select a valid city in ${state}`;
  }

  return {
    isValid: Object.keys(errors).length === 0,
    errors,
  };
};
